[package]
name = "date_type_detector"
version = "0.1.0"
edition = "2021"

[lib]
name = "date_type_detector"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
chrono = "0.4"
once_cell = "1.19"